databases:
  - name: SnowfallDB
    plan: free
    databaseName: SnowfallDB
    user: ad

services:
  - type: web
    plan: free
    name: SnowfallDB
    runtime: python3
    buildCommand: './build.sh'
    startCommand: 'python3 -m gunicorn love_project.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: SnowfallDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4