name: Django CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Microsoft ODBC Driver 17 for SQL Server
      run: |
        # Clean up any existing Microsoft repositories to avoid conflicts
        sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
        sudo rm -f /etc/apt/sources.list.d/mssql-release.list
        
        # Update package lists
        sudo apt-get update
        
        # Install prerequisites
        sudo apt-get install -y curl gnupg lsb-release
        
        # Add Microsoft signing key
        curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
        
        # Add Microsoft SQL Server repository
        echo "deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/ubuntu/$(lsb_release -rs)/prod $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/mssql-release.list
        
        # Update package lists
        sudo apt-get update
        
        # Install ODBC driver and development headers
        sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17
        sudo apt-get install -y unixodbc-dev
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        python manage.py migrate

    - name: Run tests for love_messages
      run: |
        python manage.py test love_messages.tests